### ISSUE TITLE
JSON: POST data should be bytes or an iterable of bytes

### ISSUE THREAD

**Issue by nhnb** [metajack/notify-webhook#14]
After changing the content type to application/json, I get the following error

```
remote: Traceback (most recent call last):
remote:   File "hooks/post-receive", line 314, in <module>
remote:     post(POST_URL, data)
remote:   File "hooks/post-receive", line 302, in post
remote:     u = opener.open(request)
remote:   File "/usr/lib/python3.4/urllib/request.py", line 462, in open
remote:     req = meth(req)
remote:   File "/usr/lib/python3.4/urllib/request.py", line 1113, in do_request_
remote:     raise TypeError(msg)
remote: TypeError: POST data should be bytes or an iterable of bytes. It cannot be of type str.
```

This seems to be related to [commit ac45d56)(ac45d569816a3f78f1d5e422c7156b6ed920d4b6) which - according to the commit message - fixed the issue for url-encoding.

**Comment by Thalhammer** [comment]
Take a look at #17 
I ran into the same issue.
